version: '3'
services:
  nginx:
    image: nginx:1.17.0
    restart: on-failure
    expose:
      - 80
    ports:
      - "80:80"
    volumes:
      - ./nginx/:/etc/nginx/conf.d/
    networks:
      - mycustomnetwork
    depends_on:
      - phpfpm
  phpfpm:
    build: php-fpm/.
    image: syedusmanali/php-fpm
    restart: on-failure
    expose:
      - 9000
    volumes:
      - ${HOST_CODEBASE_DIR:-/var/www/html/}:/var/www/codebase
    networks:
      - mycustomnetwork
  mysql:
    image: mysql:5.7
    restart: on-failure
    expose:
      - 3306
    ports:
      - 3306:3306
    volumes:
      - database_data:/var/lib/mysql
    networks:
      - mycustomnetwork
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-rootpassword}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-mydatabase}
      MYSQL_USER: ${MYSQL_USER:-siteusername}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-sitepassword}
volumes:
  database_data:
    driver: local
networks:
  mycustomnetwork: ~
